name: Publish package to JSR
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i --omit=dev
      - name: Publish package
        run: npx jsr publish